//! montrs-icons collection codegen.
//!
//! Downloads the upstream SVG tarballs from GitHub (codeload), extracts only
//! the `.svg` files, and generates:
//!   - `../src/collections/data.rs` — the per-collection `CollectedGlyph` tables
//!   - `../src/collections/catalog.rs` — collection metadata + helpers
//!   - `THIRD_PARTY_NOTICES.md` — license compliance records (root of the repo)
//!
//! Pure Rust: the only external dependencies are crates.io (ureq, flate2, tar).
//! No node, no JS, no Python. Run: `cargo run --manifest-path codegen/Cargo.toml`

use std::collections::BTreeMap;
use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};

/// (key, repo, branch, in-repo svg path prefix, spdx, author, source URL,
///  style, mono)
/// `style`: "stroke" (stroke-based outlines), "fill" (filled paths),
/// "mixed" (per-path fill/stroke, like Radix — paths self-describe).
/// `mono`: for fill sets, rewrite every explicit path fill to `currentColor`
/// so the site's color control and themes can tint them.
const COLLECTIONS: &[(&str, &str, &str, &str, &str, &str, &str, &str, bool)] =
    &[
        (
            "radix",
            "radix-ui/icons",
            "main",
            "packages/radix-icons/icons",
            "MIT",
            "WorkOS (Radix UI)",
            "https://github.com/radix-ui/icons",
            "mixed",
            false,
        ),
        (
            "tabler",
            "tabler/tabler-icons",
            "main",
            "icons/outline",
            "MIT",
            "Paweł Kuna",
            "https://github.com/tabler/tabler-icons",
            "stroke",
            false,
        ),
        (
            "iconoir",
            "iconoir-icons/iconoir",
            "main",
            "icons",
            "MIT",
            "Iconoir contributors",
            "https://github.com/iconoir-icons/iconoir",
            "stroke",
            false,
        ),
        (
            "phosphor",
            "phosphor-icons/core",
            "main",
            "assets/regular",
            "MIT",
            "Phosphor Icons contributors",
            "https://github.com/phosphor-icons/core",
            "stroke",
            false,
        ),
        (
            "mdi",
            "Templarian/MaterialDesign",
            "master",
            "svg",
            "Apache-2.0",
            "Austin Andrews (Templarian)",
            "https://github.com/Templarian/MaterialDesign",
            "fill",
            false,
        ),
        (
            "bootstrap",
            "twbs/icons",
            "main",
            "icons",
            "MIT",
            "The Bootstrap Authors",
            "https://github.com/twbs/icons",
            "fill",
            false,
        ),
        (
            "simple-icons",
            "simple-icons/simple-icons",
            "develop",
            "icons",
            "CC0-1.0",
            "Simple Icons Contributors",
            "https://github.com/simple-icons/simple-icons",
            "fill",
            true,
        ),
        (
            "cryptocurrency",
            "spothq/cryptocurrency-icons",
            "master",
            "svg/black",
            "CC0-1.0",
            "Spothq contributors",
            "https://github.com/spothq/cryptocurrency-icons",
            "fill",
            true,
        ),
    ];

struct CollectionSpec {
    key: &'static str,
    repo: &'static str,
    branch: &'static str,
    prefix: &'static str,
    license: &'static str,
    author: &'static str,
    url: &'static str,
    style: &'static str,
    mono: bool,
}

struct ParsedIcon {
    name: String,
    svg: String,     // inner markup
    viewbox: String, // e.g. "0 0 24 24"
    fill: String,    // "none" | "currentColor" | explicit
    stroke: String,  // "none" | "currentColor" | explicit
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let crate_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let cache_dir = crate_dir.join("cache");
    fs::create_dir_all(&cache_dir)?;
    let out_dir = crate_dir.join("../src/collections");
    fs::create_dir_all(&out_dir)?;
    // codegen/ → icons/ → packages/ → repo root
    let repo_root = crate_dir.join("../../..");
    let repo_root = repo_root
        .canonicalize()
        .unwrap_or_else(|_| crate_dir.join("../../.."));

    let spec_list: Vec<CollectionSpec> = COLLECTIONS
        .iter()
        .map(|(k, r, b, p, l, a, u, s, m)| CollectionSpec {
            key: k,
            repo: r,
            branch: b,
            prefix: p,
            license: l,
            author: a,
            url: u,
            style: s,
            mono: *m,
        })
        .collect();

    let mut notices: Vec<String> = Vec::new();
    let mut all_counts: Vec<(String, usize)> = Vec::new();
    let mut data_out = String::new();
    let mut catalog_out = String::new();

    data_out.push_str("// @generated by montrs-icons-codegen. DO NOT EDIT.\n\n");
    data_out.push_str("use super::CollectedGlyph;\n\n");

    for spec in &spec_list {
        let tarball = fetch_tarball(spec, &cache_dir)?;
        let mut icons = extract_icons(spec, &tarball)?;
        for icon in &mut icons {
            normalize_style(icon, spec.style, spec.mono);
        }
        let count = icons.len();
        all_counts.push((spec.key.to_string(), count));
        let table_name = format!("{}_ICONS", spec.key.to_uppercase().replace('-', "_"));

        // Emit the table for this collection.
        data_out.push_str(&format!("#[cfg(feature = \"col-{}\")]\n", spec.key));
        data_out.push_str(&format!(
            "pub static {table_name}: &[CollectedGlyph] = &[\n"
        ));
        for icon in &icons {
            data_out.push_str(&format!(
                "    CollectedGlyph {{ name: \"{}\", svg: \"{}\", viewbox: \"{}\", \
                 fill: \"{}\", stroke: \"{}\" }},\n",
                escape(&icon.name),
                escape(&icon.svg),
                escape(&icon.viewbox),
                escape(&icon.fill),
                escape(&icon.stroke),
            ));
        }
        data_out.push_str("];\n\n");

        // Notice entry (full license text appended from the archive LICENSE).
        let license_text = find_license(&spec, &tarball).unwrap_or_else(|| {
            format!("See {} for the {} license text.", spec.url, spec.license)
        });
        notices.push(format!(
            "### {}\n\n- Source: {}\n- License: {}\n- Author/Copyright: {}\n- Icons embedded: {}\n\n```\n{}\n```\n",
            spec.url.rsplit('/').next().unwrap_or(spec.key),
            spec.url,
            spec.license,
            spec.author,
            count,
            license_text,
        ));

        println!("{} → {} icons", spec.key, count);
    }

    // Write catalog.rs (collection metadata + browsing helper).
    catalog_out.push_str("// @generated by montrs-icons-codegen. DO NOT EDIT.\n\n");
    catalog_out.push_str(&format!(
        "pub const COLLECTION_LIST: &[CollectionInfo] = &[\n"
    ));
    for spec in &spec_list {
        catalog_out.push_str(&format!(
            "    CollectionInfo {{ key: \"{}\", label: \"{}\", license: \"{}\", source: \"{}\" }},\n",
            spec.key,
            title_case(spec.key),
            spec.license,
            spec.url,
        ));
    }
    catalog_out.push_str("];\n");
    fs::write(out_dir.join("catalog.rs"), catalog_out)?;

    fs::write(out_dir.join("data.rs"), data_out)?;

    // THIRD_PARTY_NOTICES.md at the repo root.
    let mut notice_file = String::new();
    notice_file.push_str("# Third-Party Notices\n\n");
    notice_file.push_str(
        "MontRS embeds icon sets from the following third parties under their own \
         permissive licenses. MontRS itself remains dual-licensed Apache-2.0 / MIT; \
         these licenses are reproduced so you can ship the icons anywhere.\n\n",
    );
    for n in &notices {
        notice_file.push_str(n);
        notice_file.push('\n');
    }
    fs::write(repo_root.join("THIRD_PARTY_NOTICES.md"), notice_file)?;

    println!(
        "\nDone. {} collections, {} icons total → src/collections/ + THIRD_PARTY_NOTICES.md",
        spec_list.len(),
        all_counts.iter().map(|(_, c)| c).sum::<usize>()
    );
    Ok(())
}

fn fetch_tarball(
    spec: &CollectionSpec,
    cache: &Path,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let target = cache.join(format!("{}.tgz", spec.key));
    if target.exists() {
        return Ok(target);
    }
    let url = format!(
        "https://codeload.github.com/{}/tar.gz/refs/heads/{}",
        spec.repo, spec.branch
    );
    println!("download {}…", spec.key);
    let response = ureq::get(&url).call()?;
    let mut bytes = Vec::new();
    response.into_reader().read_to_end(&mut bytes)?;
    fs::write(&target, &bytes)?;
    Ok(target)
}

fn extract_icons(
    spec: &CollectionSpec,
    tarball: &Path,
) -> Result<Vec<ParsedIcon>, Box<dyn std::error::Error>> {
    let file = fs::File::open(tarball)?;
    let gz = flate2::read::GzDecoder::new(file);
    let mut archive = tar::Archive::new(gz);
    let mut out = Vec::new();
    for entry in archive.entries()? {
        let mut e = entry?;
        let path = e.path()?.into_owned();
        if path.extension().and_then(|e| e.to_str()) != Some("svg") {
            continue;
        }
        if !path_has_prefix(&path, spec.prefix) {
            continue;
        }
        let mut content = String::new();
        e.read_to_string(&mut content)?;
        if let Some(icon) = parse_svg(&path, &content) {
            out.push(icon);
        }
    }
    out.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(out)
}

/// Does the archive path contain the in-repo prefix as a component sequence?
fn path_has_prefix(path: &Path, prefix: &str) -> bool {
    let comps: Vec<String> = path
        .components()
        .filter_map(|c| c.as_os_str().to_str().map(|s| s.to_string()))
        .collect();
    let pre: Vec<&str> = prefix.split('/').collect();
    if pre.is_empty() {
        return true;
    }
    comps.windows(pre.len()).any(|w| w.iter().eq(pre.iter()))
}

fn parse_svg(path: &Path, content: &str) -> Option<ParsedIcon> {
    let name = path.file_stem()?.to_str()?.to_string();
    // Some upstreams (tabler) prefix the SVG with an HTML comment — start at
    // the actual `<svg` tag and take its matching close `>`.
    let svg_start = content.find("<svg")?;
    let open_end_rel = content[svg_start..].find('>')?;
    let open_end = svg_start + open_end_rel;
    let root = &content[svg_start..open_end];
    let viewbox = attr(root, "viewBox").or_else(|| {
        let w = attr(root, "width")?;
        let h = attr(root, "height")?;
        Some(format!("0 0 {w} {h}"))
    })?;
    let inner_start = open_end + 1;
    let inner_end = content.rfind("</svg>")?;
    let svg = content[inner_start..inner_end].trim().to_string();
    if svg.is_empty() {
        return None;
    }
    let fill = attr(root, "fill").unwrap_or_else(|| "none".to_string());
    let stroke = attr(root, "stroke").unwrap_or_else(|| "currentColor".to_string());
    let mut name = name;
    // strip a trailing weight suffix, e.g. phosphor "acorn-regular" → "acorn"
    for suffix in ["-regular", "-outline", "-stroke"] {
        if let Some(stripped) = name.strip_suffix(suffix) {
            name = stripped.to_string();
            break;
        }
    }
    Some(ParsedIcon {
        name,
        svg,
        viewbox,
        fill,
        stroke,
    })
}

/// Normalize a glyph's root style so the rendering pipeline can rely on a
/// single convention: stroke-based sets use `fill="none" stroke="currentColor"`
/// and get a stroke width; fill-based sets use `fill="currentColor" stroke="none"`
/// and ignore stroke width; mixed sets (Radix) leave both neutral because the
/// paths carry their own fill/stroke attributes.
fn normalize_style(icon: &mut ParsedIcon, style: &str, mono: bool) {
    match style {
        "stroke" => {
            icon.fill = "none".to_string();
            icon.stroke = "currentColor".to_string();
        }
        "fill" => {
            icon.fill = "currentColor".to_string();
            icon.stroke = "none".to_string();
            if mono {
                icon.svg = strip_title(&monoize(&icon.svg));
            }
        }
        "mixed" => {
            icon.fill = "none".to_string();
            icon.stroke = "none".to_string();
        }
        _ => {}
    }
}

/// Rewrite every explicit `fill="#RRGGBB"` on inner elements to
/// `fill="currentColor"` so theme colors can tint monochrome sets.
fn monoize(svg: &str) -> String {
    let mut out = String::with_capacity(svg.len());
    let mut rest = svg;
    while let Some(idx) = rest.find("fill=\"#") {
        out.push_str(&rest[..idx + 6]);
        let after = &rest[idx + 6..];
        match after.find('"') {
            Some(end) => {
                out.push_str("currentColor");
                out.push('"');
                rest = &after[end + 1..];
            }
            None => {
                out.push_str(after);
                break;
            }
        }
    }
    out.push_str(rest);
    out
}

/// Remove `<title>…</title>` elements (Simple Icons embeds them).
fn strip_title(svg: &str) -> String {
    let mut out = String::with_capacity(svg.len());
    let mut rest = svg;
    while let Some(idx) = rest.find("<title") {
        out.push_str(&rest[..idx]);
        match rest[idx..].find("</title>") {
            Some(close) => rest = &rest[idx + close + 8..],
            None => return out,
        }
    }
    out.push_str(rest);
    out
}

/// Naive but sufficient attribute pull from a tag string.
fn attr(tag: &str, key: &str) -> Option<String> {
    let pat = format!("{key}=\"");
    let start = tag.find(&pat)?;
    let after = start + pat.len();
    let end = tag[after..].find('"')? + after;
    Some(tag[after..end].to_string())
}

fn find_license(
    spec: &CollectionSpec,
    tarball: &Path,
) -> Option<String> {
    let file = fs::File::open(tarball).ok()?;
    let gz = flate2::read::GzDecoder::new(file);
    let mut archive = tar::Archive::new(gz);
    let mut candidates: Vec<String> = Vec::new();
    for entry in archive.entries().ok()? {
        let mut e = entry.ok()?;
        let p = e.path().ok()?.into_owned();
        let fname = p.file_name()?.to_str()?.to_uppercase();
        if fname.starts_with("LICENSE") || fname.starts_with("COPYING") {
            let mut s = String::new();
            if e.read_to_string(&mut s).is_ok() {
                candidates.push(s);
            }
        }
    }
    // Prefer the shortest (root-level) license file.
    candidates.sort_by_key(|s| s.len());
    candidates.into_iter().next()
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn title_case(s: &str) -> String {
    s.split('-')
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

#[allow(dead_code)]
fn _keep(_: BTreeMap<String, ()>) {}